#ifndef _MOSQUITO_KILLING_STATISTICS_H
#define _MOSQUITO_KILLING_STATISTICS_H


#include "app_config.h"

#if (APP_MOSQUITO_KILLING_ENABLE == 1)
#include "cobra_system.h"


#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_PIN_NUM    GPIO_PIN_30

#if (APP_MOSQUITO_KILLING_DETECT_DIFF_ENABLE == 1)
/*与buf平均的变化量delta*/
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  55
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  50
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  40
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  35


#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  200
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  100
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  50
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  25
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  30

#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  7
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  2
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  1  /*会有误发*/

#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MIN  1
#elif (APP_MOSQUITO_KILLING_DETECT_AVERAGE_DIFF_ENABLE == 1)
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  55
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  50
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  40
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  35


#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  200
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  100
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  50
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  25
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  30

#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_AVERAGE_BUFFER_MAX  50


#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_DIFF_MAX  50
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_DIFF_MIN  3
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_DIFF_MIN  1

#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  5
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  2
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  1  /*会有误发*/

#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MIN  1

#if (APP_MOSQUITO_KILLING_DETECT_LIMIT_ENABLE == 1)
/*5MIN=3000S=300*1000/2*/
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_TIME_LIMIT  (5*60*1000/2)  
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_COUNT_LIMIT  2
#endif

#if (APP_MOSQUITO_KILLING_DETECT_LINEAR_ENABLE == 1)
/*5MIN=3000S=300*1000/2*/
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LINEAR_TIME_LIMIT  (5*60*1000/2)  
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LINEAR_TIME_LIMIT  (20*60*1000/2)  
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LINEAR_TIME_LIMIT  (40*60*1000/2)  

/*定义线性比例的时间, 单位分钟*/
#define APP_MOSQUITO_KILLING_LINEAR_RATIO_TIME  12
//#define APP_MOSQUITO_KILLING_LINEAR_RATIO_TIME  11
//#define APP_MOSQUITO_KILLING_LINEAR_RATIO_TIME  10
//#define APP_MOSQUITO_KILLING_LINEAR_RATIO_TIME  9

#define APP_MOSQUITO_KILLING_LINEAR_BASE  100
#endif

#else
/*与buf平均的变化量delta*/
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  30
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_LIMIT  35


#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  200
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  50
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  25
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_BUFFER_MAX  20

//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  3
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  2
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_VALID_COUNT_MAX  1  /*会有误发*/
#endif

/*注意使用的定时器单位*/
/*unit ms*/
#if (APP_MOSQUITO_KILLING_DETECT_ADC_5MS_PERIOD_ENABLE == 1)
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_PERIOD  2
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_PERIOD  5
#else
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_PERIOD  5
#endif

//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_INTERVAL_MAX  (100/APP_MOSQUITO_KILLING_HV_ADC_DETECT_PERIOD) 
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_INTERVAL_MAX  (200) 

/*200* 10MS*/
#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_POWER_SWITCH_COUNT_DELAY  500
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_POWER_SWITCH_COUNT_DELAY  200
//#define APP_MOSQUITO_KILLING_HV_ADC_DETECT_POWER_SWITCH_COUNT_DELAY  100

void app_mosquito_killing_ADC_Init(void);
uint32_t app_mosquito_killing_ADC_voltage(void);


#endif  /* APP_MOSQUITO_KILLING_ENABLE */

#endif  /* _MOSQUITO_KILLING_STATISTICS_H */

